//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdMesh.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdMesh.Localisation.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average cpc.
        /// </summary>
        public static string Ads_AverageCpc {
            get {
                return ResourceManager.GetString("Ads_AverageCpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clicks.
        /// </summary>
        public static string Ads_Clicks {
            get {
                return ResourceManager.GetString("Ads_Clicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctr.
        /// </summary>
        public static string Ads_Ctr {
            get {
                return ResourceManager.GetString("Ads_Ctr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ecpm.
        /// </summary>
        public static string Ads_Ecpm {
            get {
                return ResourceManager.GetString("Ads_Ecpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impressions.
        /// </summary>
        public static string Ads_Impressions {
            get {
                return ResourceManager.GetString("Ads_Impressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string App_About {
            get {
                return ResourceManager.GetString("App_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close.
        /// </summary>
        public static string App_Close {
            get {
                return ResourceManager.GetString("App_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string App_Email {
            get {
                return ResourceManager.GetString("App_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string App_Error {
            get {
                return ResourceManager.GetString("App_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last month.
        /// </summary>
        public static string App_LastMonth {
            get {
                return ResourceManager.GetString("App_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last week.
        /// </summary>
        public static string App_LastWeek {
            get {
                return ResourceManager.GetString("App_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string App_Loading {
            get {
                return ResourceManager.GetString("App_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string App_Login {
            get {
                return ResourceManager.GetString("App_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string App_None {
            get {
                return ResourceManager.GetString("App_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open.
        /// </summary>
        public static string App_Open {
            get {
                return ResourceManager.GetString("App_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overall.
        /// </summary>
        public static string App_Overall {
            get {
                return ResourceManager.GetString("App_Overall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string App_Password {
            get {
                return ResourceManager.GetString("App_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string App_Refresh {
            get {
                return ResourceManager.GetString("App_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string App_Report {
            get {
                return ResourceManager.GetString("App_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string App_Reports {
            get {
                return ResourceManager.GetString("App_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to revenue.
        /// </summary>
        public static string App_Revenue {
            get {
                return ResourceManager.GetString("App_Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this month.
        /// </summary>
        public static string App_ThisMonth {
            get {
                return ResourceManager.GetString("App_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this week.
        /// </summary>
        public static string App_ThisWeek {
            get {
                return ResourceManager.GetString("App_ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string App_Today {
            get {
                return ResourceManager.GetString("App_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string App_Yesterday {
            get {
                return ResourceManager.GetString("App_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Custom_Report_App {
            get {
                return ResourceManager.GetString("Custom_Report_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string Custom_Report_EndDate {
            get {
                return ResourceManager.GetString("Custom_Report_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All time report.
        /// </summary>
        public static string Custom_Report_IsOverall {
            get {
                return ResourceManager.GetString("Custom_Report_IsOverall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See report.
        /// </summary>
        public static string Custom_Report_SeeReport {
            get {
                return ResourceManager.GetString("Custom_Report_SeeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Custom_Report_StartDate {
            get {
                return ResourceManager.GetString("Custom_Report_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection..
        /// </summary>
        public static string Error_NoConnection {
            get {
                return ResourceManager.GetString("Error_NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Report available..
        /// </summary>
        public static string Error_NoReport {
            get {
                return ResourceManager.GetString("Error_NoReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured..
        /// </summary>
        public static string Error_UnknownError {
            get {
                return ResourceManager.GetString("Error_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading dashboard.
        /// </summary>
        public static string Home_LoadingDashboard {
            get {
                return ResourceManager.GetString("Home_LoadingDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue today.
        /// </summary>
        public static string Home_TodaysRevenue {
            get {
                return ResourceManager.GetString("Home_TodaysRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email and password..
        /// </summary>
        public static string Login_Form_Data_Incorrect {
            get {
                return ResourceManager.GetString("Login_Form_Data_Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Sidebar_About {
            get {
                return ResourceManager.GetString("Sidebar_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string Sidebar_Applications {
            get {
                return ResourceManager.GetString("Sidebar_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Report.
        /// </summary>
        public static string Sidebar_CustomReport {
            get {
                return ResourceManager.GetString("Sidebar_CustomReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Sidebar_General {
            get {
                return ResourceManager.GetString("Sidebar_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Sidebar_Rate {
            get {
                return ResourceManager.GetString("Sidebar_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Sidebar_Reports {
            get {
                return ResourceManager.GetString("Sidebar_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Sidebar_Settings {
            get {
                return ResourceManager.GetString("Sidebar_Settings", resourceCulture);
            }
        }
    }
}
